// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for test server",
    "title": "Template for http server",
    "version": "1.0.0"
  },
  "host": "localhost:8000",
  "basePath": "/api/v1",
  "paths": {
    "/version": {
      "get": {
        "tags": [
          "version"
        ],
        "summary": "Get version of server",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Response.Version"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Response.Error": {
      "type": "object",
      "title": "Error response",
      "properties": {
        "code": {
          "type": "integer",
          "format": "uint32",
          "example": 400
        },
        "message": {
          "type": "string",
          "example": "some error"
        }
      }
    },
    "Response.Version": {
      "type": "object",
      "title": "Version response",
      "properties": {
        "branch": {
          "type": "string",
          "example": "main"
        },
        "build_time": {
          "type": "string",
          "example": "2021-03-06_22:22:44_MSK"
        },
        "commit": {
          "type": "string",
          "example": "6c8d084825ef4281094bd1bf26003e9a057c3305"
        },
        "version": {
          "type": "string",
          "example": "v1.0.0"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for test server",
    "title": "Template for http server",
    "version": "1.0.0"
  },
  "host": "localhost:8000",
  "basePath": "/api/v1",
  "paths": {
    "/version": {
      "get": {
        "tags": [
          "version"
        ],
        "summary": "Get version of server",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Response.Version"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Response.Error": {
      "type": "object",
      "title": "Error response",
      "properties": {
        "code": {
          "type": "integer",
          "format": "uint32",
          "example": 400
        },
        "message": {
          "type": "string",
          "example": "some error"
        }
      }
    },
    "Response.Version": {
      "type": "object",
      "title": "Version response",
      "properties": {
        "branch": {
          "type": "string",
          "example": "main"
        },
        "build_time": {
          "type": "string",
          "example": "2021-03-06_22:22:44_MSK"
        },
        "commit": {
          "type": "string",
          "example": "6c8d084825ef4281094bd1bf26003e9a057c3305"
        },
        "version": {
          "type": "string",
          "example": "v1.0.0"
        }
      }
    }
  }
}`))
}
